"""usernamecart

Revision ID: 17534b1b0366
Revises: 4be7de40a9e8
Create Date: 2020-05-15 13:09:37.825938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17534b1b0366'
down_revision = '4be7de40a9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'username')
    # ### end Alembic commands ###
