"""meerpizza

Revision ID: 18cf85555d68
Revises: 357d86bdb7f1
Create Date: 2020-05-19 15:20:08.353101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cf85555d68'
down_revision = '357d86bdb7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rpizza', sa.Column('price10', sa.Float(precision=5), nullable=True))
    op.add_column('rpizza', sa.Column('price9', sa.Float(precision=5), nullable=True))
    op.add_column('spizza', sa.Column('price10', sa.Float(precision=5), nullable=True))
    op.add_column('spizza', sa.Column('price9', sa.Float(precision=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spizza', 'price9')
    op.drop_column('spizza', 'price10')
    op.drop_column('rpizza', 'price9')
    op.drop_column('rpizza', 'price10')
    # ### end Alembic commands ###
