"""paid cart

Revision ID: 77a909a07ac9
Revises: 17534b1b0366
Create Date: 2020-05-18 21:27:27.536928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a909a07ac9'
down_revision = '17534b1b0366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'paid')
    # ### end Alembic commands ###
