"""datetimeorder

Revision ID: 91ca36fd9b34
Revises: bf8ef210b940
Create Date: 2020-05-19 14:00:22.390720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ca36fd9b34'
down_revision = 'bf8ef210b940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'date')
    # ### end Alembic commands ###
