"""ordernumber

Revision ID: ebf9bcbeefcc
Revises: c0881498dd0a
Create Date: 2020-05-28 15:57:00.267632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf9bcbeefcc'
down_revision = 'c0881498dd0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ordernumber', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'ordernumber')
    # ### end Alembic commands ###
